server:
  port: 8003
  servlet:
    context-path: /catalog/

spring:
  zipkin:
    base-url: http://zipkin-service:9411/
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: catalog
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      
  cloud:
    config:
      profile: dev
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-service
    port: 5672
queue:
  movie:
    name: movieQueue

eureka:
  instance:
    hostname: catalog-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

   
