server:
  port: 8080
  
spring:  
  zipkin:
    base-url: http://zipkin-service:9411/
  cloud:
    config:
      profile: dev
      
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: serie-service
          uri: http://serie-service:8002
          predicates:
                - Path=/serie/**
        - id: movie-service
          uri: http://movie-service:8001
          predicates:
            - Path=/movies/**
        - id: catalog-service
          uri: http://catalog-service:8003
          predicates:
            - Path=/catalog/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog

eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

