server:
  port: 8082
spring:
    datasource:
        username: root
        password: ${DATA_BASE_PASSWORD}
        url: jdbc:mysql://localhost/3306/provabackend
    jpa:
      hibernate:
        ddl-auto: update
