server:
  port: 8082
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: ${DATA_BASE_PASSWORD:Cgx1123581321}
        url: jdbc:mysql://localhost:3306/databaseprova
    jpa:
      hibernate:
        ddl-auto: update
