server:
  port: 8002
spring:
    datasource:
        username: user
        password: ${DATA_BASE_PASSWORD:password}
        url: "jdbc:mysql://localhost:3306/provajava?createDatabaseIfNotExist=true"
    jpa:
      hibernate:
        ddl-auto: update
