server:
  port: 8082
spring:
    datasource:
        username: ${DATABASE_USER:root}
        password: ${DATA_BASE_PASSWORD:Cgx1123581321}
        url: ${DATA_BASE_URL:jdbc:mysql://localhost/3306/ProvaBackend}
