server:
  port: 8082
spring:
    datasource:
        username: provaback
        password: ${DATA_BASE_PASSWORD}
        url: jdbc:mysql://localhost/3306/ProvaBackend
    jpa:
      hibernate:
        ddl-auto: update
