server:
  port: 8082
spring:
    datasource:
        username: root
        password: ${DATA_BASE_PASSWORD}
        url: jdbc:mysql://localhost:3306/DatabaseProva
    jpa:
      hibernate:
        ddl-auto: update
